version: "3.7"
services:
  tokens:
    build: 
      context: ./tokens
      target: builder 
    volumes:
      - "./tokens:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  permissions:
    build:
      context: ./permissions
    depends_on:
      - graphdb
  graphdb:
    image: arangodb
    environment:
      - ARANGO_NO_AUTH=1
  redis:
    image: redis
    ports: 
      - "6379:6379"
