version: "3.7"
services:
  tokens:
    build: ./tokens
    depends_on:
      - redis
  permissions:
    build:
      context: ./permissions
    depends_on:
      - graphdb
  graphdb:
    image: arangodb
    environment:
      - ARANGO_NO_AUTH=1
  redis:
    image: redis
